#!/bin/bash
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

if [ $# -eq 1 ] && [ "$1" == "install" ]; then
  cp "$0" -t .git/hooks/
  exit 0
fi

FILE="misc/force-version.txt"

if ! grep 'dev' "$FILE" &> /dev/null; then
  exit 0
fi

VERSION=$(sed -E 's/:::.*//' "$FILE")
TIME=$(date +"%Y-%m-%d_%H:%M:%S")

printf "%s:::%s\n" "$VERSION" "$TIME" > "$FILE"

git add "$FILE"
