# List of required tools
# requirements are checked during build
# commented requirements are ignored

requirements:
  - curl-config
  - dos2unix
  - g++
  - gcc
  - gdal-config
  - gdal_calc.py
  - gdal_edit.py
  - gdal_merge.py
  - gdal_rasterize
  - gdal_translate
  - gdaladdo
  - gdalbuildvrt
  - gdalinfo
  - gdalwarp
  - gdalsrsinfo
  - gsl-config
  - landsatlinks
  - lockfile-create
  - lockfile-remove
  - ogr2ogr
  - ogrinfo
  - opencv_version
  - parallel
  - pip3
  - python3
  - R
  - rename
  - tar
  - unzip
